[tool.poetry]
name = "ai-adventurer"
version = "0.1.0"
description = "Supposedly an offline AI adventurer, with a somewhat fancy CLI GUI."
authors = ["Joakim Hovlandsvåg <joakim.hovlandsvag@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
jax = "^0.4.30"
tensorflow = "^2.16.2"
keras = "^3.4.1"
keras-nlp = "^0.14.0"
tensorflow-datasets = "^4.9.6"
blessed = "^1.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
