[tool.poetry]
name = "ai-adventurer"
version = "0.1.0"
description = ""
authors = ["Joakim Hovlandsvåg <joakim.hovlandsvag@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
tensorflow = "^2.16.2"
keras = "^3.4.1"
keras-nlp = "^0.14.0"
jax = "^0.4.30"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
