[tool.poetry]
name = "ai-adventurer"
version = "0.9.0"
description = "Supposedly a CLI story helper game using AI services, mostly just to test"
authors = ["Joakim Hovlandsvåg <joakim.hovlandsvag@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
jax = "^0.4.30"
tensorflow = "^2.16.2"
keras = "^3.4.1"
keras-nlp = "^0.14.0"
tensorflow-datasets = "^4.9.6"
blessed = "^1.20.0"
openai = "^1.36.1"
google-generativeai = "^0.7.2"
sqlalchemy = "^2.0.31"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
